# Generated by Django 4.2.27 on 2025-12-13 13:02

from django.db import migrations, models
import streaming.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('video', models.FileField(upload_to='videos/', validators=[streaming.models.validate_video_file])),
            ],
        ),
    ]
