# Generated by Django 4.2.27 on 2025-12-17 10:22

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('streaming', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='video',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='video',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='video',
            name='processing',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='video',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.CreateModel(
            name='VideoVariant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resolution', models.CharField(choices=[('2160p', 'UHD_4K (2160p)'), ('1080p', 'FHD (1080p)'), ('720p', 'HD (720p)'), ('480p', 'SD (480p)'), ('360p', 'LOW (360p)')], max_length=20)),
                ('file', models.FileField(upload_to='videos/variants/%Y/%m/%d/')),
                ('video', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variants', to='streaming.video')),
            ],
        ),
        migrations.CreateModel(
            name='CurrentEncode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('video_variant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='streaming.videovariant')),
            ],
        ),
    ]
