# Generated by Django 4.2.27 on 2026-01-02 09:37

from django.db import migrations, models
import streaming.models


class Migration(migrations.Migration):

    dependencies = [
        ('streaming', '0002_alter_video_options_video_created_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='videovariant',
            name='video',
        ),
        migrations.AddField(
            model_name='video',
            name='dash_base_path',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='video',
            name='dash_manifest',
            field=models.FileField(blank=True, null=True, upload_to='videos/dash/'),
        ),
        migrations.AddField(
            model_name='video',
            name='dash_ready',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='video',
            name='duration',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='video',
            name='video',
            field=models.FileField(upload_to='videos/originals/', validators=[streaming.models.validate_video_file]),
        ),
        migrations.DeleteModel(
            name='CurrentEncode',
        ),
        migrations.DeleteModel(
            name='VideoVariant',
        ),
    ]
